version: 2.1

executors:
  golang-executor:
    docker:
      - image: cimg/go:1.20  # Menentukan image Docker untuk executor, dalam hal ini menggunakan image Go versi 1.20
    working_directory: ~/app  # Menetapkan direktori kerja untuk executor

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint  # Menentukan image Docker untuk linting Dockerfile menggunakan hadolint
    steps:
      - checkout  # Checkout kode dari repository
      - run: hadolint Dockerfile  # Menjalankan perintah linting terhadap Dockerfile untuk memastikan kualitas Dockerfile

  test-app:
    executor: golang-executor  # Menentukan executor untuk menjalankan job test-app menggunakan golang-executor
    steps:
      - checkout  # Checkout kode dari repository
      - run: go mod download  # Mengunduh dependensi Go
      - run: go test -v -short --count=1 $(go list ./...)  # Menjalankan unit test untuk aplikasi Go

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable  # Menentukan image Docker untuk job build, menggunakan image base yang stabil
    steps:
      - checkout  # Checkout kode dari repository
      - setup_remote_docker  # Menyiapkan remote Docker untuk menjalankan perintah Docker dalam job
      - run:
          name: Docker login
          command: echo "$GHCR_TOKEN" | docker login ghcr.io -u huseinaby --password-stdin  # Login ke GitHub Container Registry menggunakan token yang disimpan dalam variabel GHCR_TOKEN
      - run: docker build -t ghcr.io/huseinaby/karsajobs:latest .  # Membangun Docker image dari Dockerfile yang ada di direktori saat ini
      - run: docker push ghcr.io/huseinaby/karsajobs:latest  # Push image yang sudah dibangun ke GitHub Container Registry

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint-dockerfile  # Job lint-dockerfile dijalankan pertama
      - test-app  # Job test-app dijalankan kedua
      - build-app-karsajobs:
          requires:
            - lint-dockerfile  # Job build-app-karsajobs baru dijalankan setelah lint-dockerfile selesai
            - test-app  # Job build-app-karsajobs baru dijalankan setelah test-app selesai
